### ISSUE TITLE
zsync{,make}2 updateinfo strings?

### ISSUE THREAD

**Issue by KurtPfeifle** [AppImage/zsync2#18]
I downloaded zsyn{,make}2 AppImages from the *AppImage/zsync2* GitHub realm:

* https://github.com/AppImage/zsync2/releases/

The files show these *updateinfo* strings:

```
gh-releases-zsync|TheAssassin|zsync2|continuous|zsync2-*x86_64.AppImage.zsync
gh-releases-zsync|TheAssassin|zsync2|continuous|zsyncmake2-*x86_64.AppImage.zsync
```

Is this how it is intended? Shouldn't the two strings have *TheAssassin* replaced by *AppImageKit*?

Or is this a real-life test for the case where a seed file is on a different location as compared to the standard download location of the respective AppImage?

**Comment by probonopd** [comment]
I think the zsync2 project was moved from the TheAssassin GitHub to the AppImage organization. Possibly the update information was inadvertently not updated in this process.

**Comment by KurtPfeifle** [comment]
I just tested it: the update does still work, even with the "wrong looking" string. I updated from 106 to 108 just now.

So even if not intended, you can log it as a passed real-life test for the case mentioned above...

**Comment by probonopd** [comment]
That is because GitHub does redirect when a project has been moved from a personal account to an organization. At least as long as you don't clone that project into your personal account again.

**Comment by KurtPfeifle** [comment]
But the project doesn't seem to have *moved*, since it is still there at *TheAssassin/zsync2*?

**Comment by probonopd** [comment]
It was moved to https://github.com/AppImage/zsync2 (check it out), https://github.com/TheAssassin/zsync2 (where it was before) now redirects there (check it out). Cool, eh? ;-)

**Comment by TheAssassin** [comment]
Thanks for spotting this. But yes, the GitHub update information type tries to implement all redirection features, and this real-world test showed it works perfectly fine.

**Comment by KurtPfeifle** [comment]
@probonopd: I could swear that a few days ago there was no re-direction I was able to spot. If I used a browser to go to https://github.com/TheAssassin/zsync2 it looked like I was right at  https://github.com/TheAssassin/zsync2 without any re-direction (location indicated by URL bar content). To me it appeared as if https://github.com/AppImage/zsync2 was just a copy. Today, I can watch the re-direction happening...

**Comment by TheAssassin** [comment]
GitHub have had this for years. Either GitHub have had a little hiccup, your browser's address bar was lagging behind, or you just didn't notice the redirection, but I assure you that the redirection has been working ever since I moved the repository.
