### ISSUE TITLE
zlib1g-dev is an undocumented build dependency

### ISSUE THREAD

**Issue by DeeDeeG** [AppImage/zsync2#34]
Hi folks,

In my experience building this project, it fails without `zlib1g-dev` installed, but it succeeds once `zlib1g-dev` is installed. Might want to add that package to the `apt-get install` step in the README.

(currently, it's: `sudo apt-get -y install git cmake g++ libssl-dev libssh2-1-dev libcurl4-gnutls-dev`)

Happy to submit as a PR if desired.

**Comment by probonopd** [comment]
A PR would be great indeed. Thanks @DeeDeeG

**Comment by DeeDeeG** [comment]
I added it as PR #35 .

**Comment by probonopd** [comment]
Thank you.

**Comment by DeeDeeG** [comment]
For the record: If anyone says they don't have `zlib.h` it's due to not having `zlib1g-dev` installed (at least on Ubuntu anyways. )

The error messages look something like this:

```c++
/home/[user]/zsync2/src/zsclient.cpp:21:14: fatal error: zlib.h: No such file or directory
     #include <zlib.h>
              ^~~~~~~~
```

**Comment by probonopd** [comment]
Documenting error messages is good practice for SEO (search engine optimization) reasons. Thanks for taking the time @DeeDeeG :+1:
