### ISSUE TITLE
How

### ISSUE THREAD

**Issue by Classic298** [AppImage/zsync2#63]
Okay let me put it simple

I have never heard of zsync2 but i wanted to update my AUR packages today and it said i cannot do so, because my local zsync2 is not an exact copy of this github repo.

I deleted my local zsync2 and cloned this repo, but then i saw that i cant even build it, because it's made for debian (according to the tutorial in the readme) and upon trying to build it, it failed.

I want to update my AUR through yay.
What should i do now?

==> ERROR: /home/<username>/.cache/yay/appimagelauncher/zsync2 is not a clone of https://github.com/TheAssassin/zsync2.git
    Aborting...

```
[USER@MACHINE build]$ cmake .. -DUSE_SYSTEM_CURL=1 -DBUILD_CPR_TESTS=0
CMake Error at lib/CMakeLists.txt:27 (add_subdirectory):
  The source directory

    /home/USER/.cache/yay/appimagelauncher/zsync2/lib/cpr

  does not contain a CMakeLists.txt file.


CMake Error at lib/CMakeLists.txt:30 (set_property):
  set_property could not find TARGET cpr.  Perhaps it has not yet been
  created.


CMake Error at lib/CMakeLists.txt:42 (add_subdirectory):
  The source directory

    /home/USER/.cache/yay/appimagelauncher/zsync2/lib/gtest

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!

```

**Comment by TheAssassin** [comment]
Cannot support third-party packaging. Please contact that AUR maintainer.

Side note: `git submodule update --init --recursive` is missing somewhere.

**Comment by TheAssassin** [comment]
P.S.: This is an AppImageLauncher package issue. That doesn't mean I would support AUR packages, though. It's the AUR maintainer's job to update their packaging.

**Comment by Classic298** [comment]
Thanks for the information though! Helpful.

I will go ask there.

And yes, i did a quick google search but couldnt find anything so far. But still, thanks :)

**Comment by TheAssassin** [comment]
https://aur.archlinux.org/packages/appimagelauncher

![screenshot_2022-06-07_00-14-22](https://user-images.githubusercontent.com/4503202/172258107-7dc93749-9907-44b3-94a9-43204ea81852.png)

**Comment by Classic298** [comment]
My god thanks. A comment on that package.. didnt fix it but gave me an idea and that did it

Combining removing the appimagelauncher and ALSO deleting all cached files fixed it for me

Great support even though you are not responsible for it

Very neat of you :)
